### ISSUE TITLE
It seems the API for ODFL has changed and i am getting a 301 when i called the API.

### ISSUE THREAD

**Issue by richzhou** [rmevans1/odfl-gem#1]
The new WSDL is at https://www.odfl.com/wsRate_v4/RateService/WEB-INF/wsdl/RateService.wsdl . Any chance you can make the GEM work for v4 (instead of v3?)

**Comment by richzhou** [comment]
I think I was using an older version of the Gem. After installing from github, i was able to get a rate. Thanks for the gem!

**Comment by rmevans1** [comment]
Yeah you had an old version of the gem... ODFL changed the way to access the wsdl file. The new version on RubyGems reflects the current url for the file.

I'm glad you're able to use the gem
